name: Super-Linter

on:
    pull_request:
        branches:
            - main

jobs:
    super-linter:
        runs-on: ubuntu-latest

        permissions:
            contents: read
            packages: read
            statuses: write

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Super-Linter
              uses: github/super-linter@v3
              env:
                  VALIDATE_ALL_CODEBASE: "false"
                  DEFAULT_BRANCH: "main"
