name: Lint Codebase

on:
    push:
        branches:
            - main

jobs:
    lint:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Run Super-Linter
              uses: super-linter/super-linter@v6.1.1
